# Generated by Django 6.0.4 on 2026-04-12 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGuidanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspiration', models.CharField(db_index=True, max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('explanation', models.TextField()),
            ],
            options={
                'verbose_name': 'Career Guidance Entry',
                'verbose_name_plural': 'Career Guidance Entries',
                'ordering': ['aspiration', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='CareerAspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspiration', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_aspirations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Aspiration',
                'verbose_name_plural': 'Career Aspirations',
                'ordering': ['-created_at'],
            },
        ),
    ]
