# Generated by Django 6.0.4 on 2026-04-12 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APSRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('subject_dependent_minimum_aps', 'Subject-dependent minimum APS')], max_length=50)),
            ],
            options={
                'verbose_name': 'APS Rule',
                'verbose_name_plural': 'APS Rules',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APSRuleCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('minimum_level', models.PositiveIntegerField()),
                ('min_aps', models.PositiveIntegerField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='qualifications.apsrule')),
            ],
            options={
                'verbose_name': 'APS Rule Condition',
                'verbose_name_plural': 'APS Rule Conditions',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('qualification_code', models.CharField(blank=True, default='', max_length=50)),
                ('faculty', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('minimum_aps', models.PositiveIntegerField()),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='qualifications.institution')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'ordering': ['institution', 'name'],
            },
        ),
        migrations.AddField(
            model_name='apsrule',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aps_rules', to='qualifications.qualification'),
        ),
        migrations.CreateModel(
            name='SelectionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('possible_portfolio', 'Possible Portfolio'), ('required_portfolio', 'Required Portfolio'), ('interview', 'Interview'), ('nbt', 'NBT'), ('other', 'Other')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_requirements', to='qualifications.qualification')),
            ],
            options={
                'verbose_name': 'Selection Requirement',
                'verbose_name_plural': 'Selection Requirements',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('mandatory', 'Mandatory'), ('one_of', 'One of (alternative)'), ('disallowed', 'Disallowed')], max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('minimum_level', models.PositiveIntegerField(default=0)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requirements', to='qualifications.qualification')),
            ],
            options={
                'verbose_name': 'Subject Requirement',
                'verbose_name_plural': 'Subject Requirements',
                'ordering': ['requirement_type', 'subject'],
            },
        ),
    ]
