# Generated by Django 6.0.4 on 2026-04-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='campus',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qualification',
            name='duration',
            field=models.CharField(blank=True, default='', help_text='e.g. 3 years, 4 years', max_length=50),
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_type',
            field=models.CharField(blank=True, default='', help_text='e.g. Bachelor Degree, BA Degree, Bachelor of Commerce Degree', max_length=100),
        ),
    ]
