# Generated by Django 6.0.4 on 2026-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portal_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'Application Entry',
                'verbose_name_plural': 'Application Entries',
                'ordering': ['institution_name'],
            },
        ),
    ]
