# Generated by Django 5.2.1 on 2025-06-30 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('UNI', 'University'), ('UoTech', 'University of Technology'), ('TVET', 'TVET College')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Hindi Home Language', 'Hindi Home Language'), ('Hindi First Additional Language', 'Hindi First Additional Language'), ('Hindi Second Additional Language', 'Hindi Second Additional Language'), ('Gujarati Home Language', 'Gujarati Home Language'), ('Gujarati First Additional Language', 'Gujarati First Additional Language'), ('Gujarati Second Additional Language', 'Gujarati Second Additional Language'), ('Tamil Home Language', 'Tamil Home Language'), ('Tamil Second Additional Language', 'Tamil Second Additional Language'), ('Tamil First Additional Language', 'Tamil First Additional Language'), ('Telegu Home Language', 'Telegu Home Language'), ('Telegu First Additional Language', 'Telegu First Additional Language'), ('Telegu Second Additional Language', 'Telegu Second Additional Language'), ('Urdu Home Language', 'Urdu Home Language'), ('Urdu First Additional Language', 'Urdu First Additional Language'), ('Urdu Second Additional Language', 'Urdu Second Additional Language'), ('Arabic Home Language', 'Arabic Home Language'), ('Arabic First Additional Language', 'Arabic First Additional Language'), ('Arabic Second Additional Language', 'Arabic Second Additional Language'), ('French Home Language', 'French Home Language'), ('French Home Additional Language', 'French Home Additional Language'), ('French Second Additional Language', 'French Second Additional Language'), ('Hebrew Home Language', 'Hebrew Home Language'), ('Hebrew Second Additional Language', 'Hebrew Second Additional Language'), ('Hebrew First Additional Language', 'Hebrew First Additional Language'), ('Italian Home Language', 'Italian Home Language'), ('Italian Second Additional Language', 'Italian Second Additional Language'), ('Italian First Additional Language', 'Italian First Additional Language'), ('Modern Greek', 'Modern Greek'), ('Serbian', 'Serbian'), ('Spanish Second Additional Language', 'Spanish Second Additional Language'), ('Latin Second Additional Language', 'Latin Second Additional Language'), ('English Home Language', 'English Home Language'), ('English First Additional Language', 'English First Additional Language'), ('English Second Additional Language', 'English Second Additional Language'), ('Portuguese Home Language', 'Portuguese Home Language'), ('German Home Language', 'German Home Language'), ('Portuguese Second Additional Language', 'Portuguese Second Additional Language'), ('Portuguese First Additional Language', 'Portuguese First Additional Language'), ('German Second Additional Language', 'German Second Additional Language'), ('Religion Studies', 'Religion Studies'), ('Information Technology', 'Information Technology'), ('South African Sign Language Home Language', 'South African Sign Language Home Language'), ('Mandarin Second Additional Language', 'Mandarin Second Additional Language'), ('Afrikaans Home Language', 'Afrikaans Home Language'), ('Afrikaans First Additional Language', 'Afrikaans First Additional Language'), ('Afrikaans Second Additional Language', 'Afrikaans Second Additional Language'), ('isiZulu Home Language', 'isiZulu Home Language'), ('isiZulu Second Additional Language', 'isiZulu Second Additional Language'), ('isiZulu First Additional Language', 'isiZulu First Additional Language'), ('isiXhosa Home Language', 'isiXhosa Home Language'), ('isiXhosa First Additional Language', 'isiXhosa First Additional Language'), ('isiXhosa Second Additional Language', 'isiXhosa Second Additional Language'), ('SiSwati Home Language', 'SiSwati Home Language'), ('SiSwati First Additional Language', 'SiSwati First Additional Language'), ('SiSwati Second Additional Language', 'SiSwati Second Additional Language'), ('isiNdebele Home Language', 'isiNdebele Home Language'), ('isiNdebele First Additional Language', 'isiNdebele First Additional Language'), ('isiNdebele Second Additional Language', 'isiNdebele Second Additional Language'), ('Sepedi Home Language', 'Sepedi Home Language'), ('Sepedi First Additional Language', 'Sepedi First Additional Language'), ('Sepedi Second Additional Language', 'Sepedi Second Additional Language'), ('Sesotho Home Language', 'Sesotho Home Language'), ('Sesotho First Additional Language', 'Sesotho First Additional Language'), ('Sesotho Second Additional Language', 'Sesotho Second Additional Language'), ('Setswana Home Language', 'Setswana Home Language'), ('Setswana First Additional Language', 'Setswana First Additional Language'), ('Setswana Second Additional Language', 'Setswana Second Additional Language'), ('Xitsonga Home Language', 'Xitsonga Home Language'), ('Xitsonga First Additional Language', 'Xitsonga First Additional Language'), ('Tshivenda Home Language', 'Tshivenda Home Language'), ('Tshivenda First Additional Language', 'Tshivenda First Additional Language'), ('Tshivenda Second Additional Language', 'Tshivenda Second Additional Language'), ('Mathematics', 'Mathematics'), ('Mathematical Literacy', 'Mathematical Literacy'), ('Technical Mathematics', 'Technical Mathematics'), ('Mandarin Second Additional Language', 'Mandarin Second Additional Language'), ('Engineering Graphics and Design', 'Engineering Graphics and Design'), ('Technical Mathematics', 'Technical Mathematics'), ('Computer Applications Technology', 'Computer Applications Technology'), ('Religion Studies', 'Religion Studies'), ('Sport and Exercise Science', 'Sport and Exercise Science'), ('Civil Technology', 'Civil Technology'), ('Information Technology', 'Information Technology'), ('Physical Sciences', 'Physical Sciences'), ('Technical Sciences', 'Technical Sciences'), ('Dance Studies', 'Dance Studies'), ('Nautical Science', 'Nautical Science'), ('Engineering Graphics and Design', 'Engineering Graphics and Design'), ('Geography', 'Geography'), ('Marine Sciences', 'Marine Sciences'), ('Mechanical Technology', 'Mechanical Technology'), ('Life Sciences', 'Life Sciences'), ('Electrical Technology', 'Electrical Technology'), ('Design', 'Design'), ('Accounting', 'Accounting'), ('Maritime Economics', 'Maritime Economics'), ('Equine Studies', 'Equine Studies'), ('Consumer Studies', 'Consumer Studies'), ('Hospitality Studies', 'Hospitality Studies'), ('Dramatic Arts', 'Dramatic Arts'), ('Tourism', 'Tourism'), ('Visual Arts', 'Visual Arts'), ('Agricultural Management Practices', 'Agricultural Management Practices'), ('Business Studies', 'Business Studies'), ('Marine Sciences', 'Marine Sciences'), ('History', 'History'), ('Agricultural Technology', 'Agricultural Technology'), ('Agricultural Sciences', 'Agricultural Sciences'), ('Music', 'Music'), ('Economics', 'Economics'), ('History', 'History')], max_length=200)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('APS', models.IntegerField(default=0)),
                ('Duration', models.IntegerField(default=0)),
                ('NBT', models.BooleanField(default=False)),
                ('Requirements', models.TextField(blank=True, max_length=200, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.institution')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ManyToManyField(through='schools.Course', to='schools.institution'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('SBS', 'School of Business Sciences'), ('Accountancy', 'The Wits Margo Steele School of Accountancy'), ('SEF', 'School of Economics and Finance'), ('Law', 'School of Law'), ('None', 'No School')], max_length=200, null=True)),
                ('faculty', models.ManyToManyField(through='schools.Course', to='schools.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='School',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='Subjects',
            field=models.ManyToManyField(to='schools.subjectchoices'),
        ),
    ]
