# Generated by Django 5.2.1 on 2025-08-13 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('UNI', 'University'), ('UoTech', 'University of Technology'), ('TVET', 'TVET College')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Arabic Home Language', 'Arabic Home Language'), ('Arabic First Additional Language', 'Arabic First Additional Language'), ('Arabic Second Additional Language', 'Arabic Second Additional Language'), ('Accounting', 'Accounting'), ('Afrikaans First Additional Language', 'Afrikaans First Additional Language'), ('Afrikaans Home Language', 'Afrikaans Home Language'), ('Afrikaans Second Additional Language', 'Afrikaans Second Additional Language'), ('Agricultural Management Practices', 'Agricultural Management Practices'), ('Agricultural Sciences', 'Agricultural Sciences'), ('Agricultural Technology', 'Agricultural Technology'), ('Business Studies', 'Business Studies'), ('Computer Applications Technology', 'Computer Applications Technology'), ('Civil Technology', 'Civil Technology'), ('Consumer Studies', 'Consumer Studies'), ('Dance Studies', 'Dance Studies'), ('Design', 'Design'), ('Dramatic Arts', 'Dramatic Arts'), ('English Home Language', 'English Home Language'), ('English First Additional Language', 'English First Additional Language'), ('English Second Additional Language', 'English Second Additional Language'), ('Economics', 'Economics'), ('Electrical Technology', 'Electrical Technology'), ('Engineering Graphics and Design', 'Engineering Graphics and Design'), ('Equine Studies', 'Equine Studies'), ('French Home Additional Language', 'French Home Additional Language'), ('French Home Language', 'French Home Language'), ('French Second Additional Language', 'French Second Additional Language'), ('Gujarati Home Language', 'Gujarati Home Language'), ('Gujarati First Additional Language', 'Gujarati First Additional Language'), ('Gujarati Second Additional Language', 'Gujarati Second Additional Language'), ('Geography', 'Geography'), ('History', 'History'), ('Hindi Home Language', 'Hindi Home Language'), ('Hindi First Additional Language', 'Hindi First Additional Language'), ('Hindi Second Additional Language', 'Hindi Second Additional Language'), ('Hebrew First Additional Language', 'Hebrew First Additional Language'), ('Hebrew Home Language', 'Hebrew Home Language'), ('Hebrew Second Additional Language', 'Hebrew Second Additional Language'), ('Hospitality Studies', 'Hospitality Studies'), ('Italian Home Language', 'Italian Home Language'), ('Italian First Additional Language', 'Italian First Additional Language'), ('Italian Second Additional Language', 'Italian Second Additional Language'), ('Information Technology', 'Information Technology'), ('isiNdebele First Additional Language', 'isiNdebele First Additional Language'), ('isiNdebele Home Language', 'isiNdebele Home Language'), ('isiNdebele Second Additional Language', 'isiNdebele Second Additional Language'), ('isiXhosa First Additional Language', 'isiXhosa First Additional Language'), ('isiXhosa Home Language', 'isiXhosa Home Language'), ('isiXhosa Second Additional Language', 'isiXhosa Second Additional Language'), ('isiZulu First Additional Language', 'isiZulu First Additional Language'), ('isiZulu Home Language', 'isiZulu Home Language'), ('isiZulu Second Additional Language', 'isiZulu Second Additional Language'), ('Life Orientation', 'Life Orientation'), ('Life Sciences', 'Life Sciences'), ('Life Orientation', 'Life Orientation'), ('Latin Second Additional Language', 'Latin Second Additional Language'), ('Mandarin Second Additional Language', 'Mandarin Second Additional Language'), ('Marine Sciences', 'Marine Sciences'), ('Maritime Economics', 'Maritime Economics'), ('Mathematical Literacy', 'Mathematical Literacy'), ('Mathematics', 'Mathematics'), ('Mechanical Technology', 'Mechanical Technology'), ('Modern Greek', 'Modern Greek'), ('Music', 'Music'), ('Nautical Science', 'Nautical Science'), ('Portuguese First Additional Language', 'Portuguese First Additional Language'), ('Portuguese Home Language', 'Portuguese Home Language'), ('Portuguese Second Additional Language', 'Portuguese Second Additional Language'), ('Physical Sciences', 'Physical Sciences'), ('Religion Studies', 'Religion Studies'), ('Sepedi First Additional Language', 'Sepedi First Additional Language'), ('Sepedi Home Language', 'Sepedi Home Language'), ('Sepedi Second Additional Language', 'Sepedi Second Additional Language'), ('Serbian', 'Serbian'), ('Sesotho First Additional Language', 'Sesotho First Additional Language'), ('Sesotho Home Language', 'Sesotho Home Language'), ('Sesotho Second Additional Language', 'Sesotho Second Additional Language'), ('Setswana First Additional Language', 'Setswana First Additional Language'), ('Setswana Home Language', 'Setswana Home Language'), ('Setswana Second Additional Language', 'Setswana Second Additional Language'), ('SiSwati First Additional Language', 'SiSwati First Additional Language'), ('SiSwati Home Language', 'SiSwati Home Language'), ('SiSwati Second Additional Language', 'SiSwati Second Additional Language'), ('South African Sign Language Home Language', 'South African Sign Language Home Language'), ('Spanish Second Additional Language', 'Spanish Second Additional Language'), ('Sport and Exercise Science', 'Sport and Exercise Science'), ('Technical Mathematics', 'Technical Mathematics'), ('Technical Sciences', 'Technical Sciences'), ('Tamil First Additional Language', 'Tamil First Additional Language'), ('Tamil Home Language', 'Tamil Home Language'), ('Tamil Second Additional Language', 'Tamil Second Additional Language'), ('Telegu First Additional Language', 'Telegu First Additional Language'), ('Telegu Home Language', 'Telegu Home Language'), ('Telegu Second Additional Language', 'Telegu Second Additional Language'), ('Tourism', 'Tourism'), ('Tshivenda First Additional Language', 'Tshivenda First Additional Language'), ('Tshivenda Home Language', 'Tshivenda Home Language'), ('Tshivenda Second Additional Language', 'Tshivenda Second Additional Language'), ('Urdu Home Language', 'Urdu Home Language'), ('Urdu First Additional Language', 'Urdu First Additional Language'), ('Urdu Second Additional Language', 'Urdu Second Additional Language'), ('Visual Arts', 'Visual Arts'), ('Xitsonga First Additional Language', 'Xitsonga First Additional Language'), ('Xitsonga Home Language', 'Xitsonga Home Language')], max_length=200)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('APS', models.IntegerField(default=0)),
                ('Duration', models.IntegerField(default=0)),
                ('NBT', models.BooleanField(default=False)),
                ('Requirements', models.TextField(blank=True, max_length=1000, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.faculty')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.institution')),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='institution',
            field=models.ManyToManyField(through='schools.Course', to='schools.institution'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty', models.ManyToManyField(through='schools.Course', to='schools.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='School',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='Subjects',
            field=models.ManyToManyField(to='schools.subjectchoices'),
        ),
    ]
