# Generated by Django 5.2.1 on 2025-06-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
